### GET all users
GET http://localhost:8080/api/v1/users
Accept: application/json

### GET user by id
GET http://localhost:8080/api/v1/users/{{userId}}
Accept: application/json

### DELETE ONE USER
DELETE http://localhost:8080/api/v1/users/{{userId}}
Accept: application/json

### CREATE ONE USER
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "userFirstName": "newUserFN",
  "userLastName": "newUserLN",
  "email": "newUserEmail@gmail.com",
  "password": "11111111",
  "nickname": "newUserNick"
}

### UPDATE ONE USER
PUT http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "id": "{{userId}}",
  "userFirstName": "UpdatedFN",
  "userLastName": "UpdatedLN",
  "email": "updatedEmail@gmail.com",
  "password": "22222222",
  "nickname": "UpdatedNick"
}

### GET HELLO USER
GET http://localhost:8080/api/v1/users/hello/user
Accept: text/plain

### GET HELLO ADMIN
GET http://localhost:8080/api/v1/users/hello/admin
Accept: text/plain

### GET HELLO UNKNOWN
GET http://localhost:8080/api/v1/users/hello/unknown
Accept: text/plain
